### ISSUE TITLE
Investigar posibles tecnologias, servicios y su por que 

### ISSUE THREAD

**Issue by JuanGQCadavid** [Que-gonorrea-parce-com/QueGonorrea#20]
Traer varias alternativas para

* front
* back
* aws services
* base de datos

**Comment by ngonza27** [comment]
Se realizo una reunion en la que se definieron las siguientes tecnologias y servicios:
* Frontend: S3 + Flutter.
* Backend: Lambda-ECR + NodeJs.
* Base de Datos: RDS - Aurora.
* Otros servicios: API Gateway, S3, Route53, ACM, CloudFront.
