### ISSUE TITLE
Diagrama arquitectonico version beta

### ISSUE THREAD

**Issue by JuanGQCadavid** [Que-gonorrea-parce-com/QueGonorrea#21]
* Proponer los microservicios
* identificar llamados entre ellos
* Relacion de microservicios

**Comment by JuanGQCadavid** [comment]
@ngonza27 First draw, any thoughts ?
![ArchitecturalOverView](https://user-images.githubusercontent.com/21164304/121452420-ff2d3f00-c964-11eb-9445-3d9072550020.png)

**Comment by ngonza27** [comment]
@JuanGQCadavid Overall it looks good for me, I'm still unclear on how to use the orchestrators. The next meeting is going to be thrilling!
