### ISSUE TITLE
Desplegar vista -> En construccion 

### ISSUE THREAD

**Issue by JuanGQCadavid** [Que-gonorrea-parce-com/QueGonorrea#23]
Poner la vista de enconstruccion en la pagina principal

**Comment by JuanGQCadavid** [comment]
No nos dio para montarlo en s3, provisionalmente esta en ec2, debemos investigar como hptas se usa route 53 con s3

**Comment by ngonza27** [comment]
Ya se pudo relacionar el url http://quegonorreaparce.com con la aplicacion situada en S3 por medio de CloudFront.

**Comment by JuanGQCadavid** [comment]
Se resolvio usando aws ceritifcado publico, tambien tiene ssl https://quegonorreaparce.com

**Comment by JuanGQCadavid** [comment]
ec2 muerto, aws limpio

**Comment by JuanGQCadavid** [comment]
El cloudfront ya esta redireccionado http a https
